/**
 * Workout history — the finished sessions, on disk.
 *
 * Until now, finishing a workout logged a line to the console. Everything the
 * user did was assembled into `SetHistory` rows, printed, and dropped: the app
 * that exists to make progressive overload visible could not remember a single
 * session it had watched. This store is where a finished workout actually goes,
 * and it is what the History section reads.
 *
 * The rules, all of them the same doctrine as `libraryStore` and the session
 * store:
 *
 *  1. NEWEST FIRST, ALWAYS. The list is read backwards from today, so the array is
 *     kept in that order rather than sorted at render time by four different
 *     screens.
 *  2. NOTHING EMPTY IS RECORDED. A session where nothing was logged is not a
 *     workout; `buildCompletedWorkout` returns null and this store writes nothing.
 *  3. FINISHING TWICE IS ONE WORKOUT. A save for an id that is already present
 *     REPLACES it. The id is the session's own, so a double-tap on Finish, or a
 *     finish that raced a rehydration, cannot produce two rows for one workout.
 *  4. WHAT COMES OFF DISK IS VALIDATED, NOT TRUSTED. A half-written blob used to be
 *     a crash on the screen that read it, and because it is persisted, a crash that
 *     came back on every launch. Malformed workouts and malformed set rows are
 *     dropped on the way in; what survives is renderable by construction. That did
 *     not change when the bytes moved into SQLite: a column can hold nonsense
 *     exactly as a JSON blob can, and there is still one guard per shape.
 *  5. THE LOG IS APPEND-MOSTLY, AND NOTHING IN HERE IS REWRITTEN BY THE APP.
 *     That sentence used to end "nothing in here is rewritten", full stop, and it
 *     is now more precise rather than weaker: the APP still never rewrites a
 *     logged set — no inference, no backfill, no rounding to a loadable weight, no
 *     re-deriving a summary against today's library. The USER can correct one row.
 *
 *     That is the one exception, and it earns it. History is the thing this app
 *     exists to be true about, and 40 kg typed where 4 was meant made it false in
 *     a way whose only remedy was deleting the workout and re-entering it — which
 *     costs the whole session, and takes those sets out of what the prefills and
 *     the suggestions read. A typo is not a workout. `updateWorkoutSet` and
 *     `deleteWorkoutSet` are the narrowest fix that reaches it: one row, one field
 *     at a time, and every derived number regenerated by `recomputeWorkout`
 *     through the same functions that built it, never by patching the rendered
 *     strings.
 *
 *     Deleting the LAST row of a workout is refused. That is deleting the workout,
 *     `deleteWorkout` already exists, and it asks first — which a set row's ✕
 *     should not have to.
 *
 * ── 6. IT LIVES IN SQLITE NOW, AND THERE IS NO CAP ──────────────────────────
 *
 * There used to be a `MAX_WORKOUTS = 250`, and its own comment was honest that it
 * was a STORAGE decision rather than a product one: AsyncStorage is one string per
 * key, every `Finish` re-serialised the entire history — every workout, every set
 * row — and wrote it back as one blob, so the cap was a guess at where that string
 * gets too big to write safely. It picked the right failure mode ("the oldest
 * workout falls off" beats "the write silently fails and the last month is gone")
 * and it was SILENT, which on an app whose value is a log long enough to show a
 * plateau is a workout lost with nothing said about it.
 *
 * `historyDb.ts` replaces the blob with two tables and the index `models.ts` has
 * described since the first release. A save is now one workout and its rows, not
 * the whole log, so the reason for the cap is gone and the cap is gone with it.
 * Nothing in this store's public interface changed: `workouts` is still the
 * newest-first array every screen reads, every action still returns what it
 * returned, and no screen was touched.
 *
 * One thing is worth knowing rather than fixing: the whole log is still held in
 * MEMORY, because `historyByExerciseId` builds its index from it and every screen
 * reads the array. That is fine at a few thousand rows and it is where a paged read
 * would slot in — `historyByExerciseId` is the one read path everything goes
 * through, which is exactly what its own comment says it is for.
 */

import { create } from 'zustand';

import {
  buildCompletedWorkout,
  recomputeWorkout,
  workoutNumbers,
  type CompletedExercise,
  type CompletedWorkout,
  type WorkoutNumberAnchor,
} from '../lib/completedWorkout';
import type { DraftSession } from '../lib/draft';
import {
  clearAllWorkouts,
  deleteWorkoutRow,
  migrateFromAsyncStorage,
  readAllWorkouts,
  readMeta,
  replaceAllWorkouts,
  writeMeta,
  writeWorkouts,
} from './historyDb';
import { currentSettings } from './settingsStore';
import type { CountUnit, ID, LoadMode, RecentSessionSummary, SetHistory } from '../types/models';

interface WorkoutHistoryState {
  /** Finished workouts, newest first. */
  workouts: CompletedWorkout[];
  /**
   * The one pinned workout number, or null for "the oldest one is 1".
   *
   * See `WorkoutNumberAnchor`: people arrive with a training history the app has
   * never seen, and one pinned pair — "this session was number 91" — is what makes
   * every other workout land on the right ordinal without editing ninety rows.
   */
  numbering: WorkoutNumberAnchor | null;

  /**
   * Record a finished session. Returns what was stored, or null if there was
   * nothing worth storing.
   */
  saveSession: (session: DraftSession, endedAt?: Date) => CompletedWorkout | null;
  deleteWorkout: (id: ID) => void;
  /**
   * Correct one logged set: its weight, its count, or its warm-up flag.
   *
   * The only write in this store that touches a row the user did not just perform,
   * and the only one that needs `recomputeWorkout` — see rule 5. Returns true when
   * something changed, so the screen can tell "corrected" from "that row is gone".
   *
   * `weightKg: null` is a real value (an unweighted set), so the patch is a partial
   * rather than a set of nullable fields: an absent key means "leave it".
   */
  updateWorkoutSet: (
    workoutId: ID,
    setId: ID,
    patch: { weightKg?: number | null; count?: number; isWarmup?: boolean },
  ) => boolean;
  /**
   * Remove one logged set. Refused for the last row of a workout — that is
   * `deleteWorkout`, which asks first. Returns false when nothing was removed.
   */
  deleteWorkoutSet: (workoutId: ID, setId: ID) => boolean;
  clearHistory: () => void;
  /**
   * Pin one workout's number. Everything before and after renumbers from it.
   *
   * A number below 1 is refused rather than clamped: "this is workout 0" is a typo
   * every time, and silently storing 1 instead would make the row the user was
   * looking at disagree with what they typed.
   */
  setWorkoutNumber: (id: ID, number: number) => void;
  /** Back to "the oldest workout is 1". */
  clearWorkoutNumbering: () => void;
  /**
   * Replace the log from a restored backup, returning how many workouts actually
   * survived validation — the honest number for the screen to report, which is not
   * necessarily the number the file claimed.
   *
   * WHOLESALE, not merged. Merging two logs sounds generous and produces a history
   * nobody can audit: the same session from two devices would appear twice unless
   * every id matched, and rule 3 of this store says finishing twice is one workout.
   * A restore is "make this phone look like that backup".
   */
  importWorkouts: (raw: unknown, numbering?: unknown) => number;
  /**
   * MERGE a log in, rather than replacing this one. Returns how many workouts were
   * actually ADDED — not how many the file held, and not the total afterwards.
   *
   * Alongside `importWorkouts`, never instead of it. Replace is right for a
   * restore: "make this phone look like that backup", and the argument on
   * `importWorkouts` about a merged LIBRARY resurrecting every exercise you have
   * deleted still stands — which is why only workouts merge, and the library and
   * settings stay replace-only.
   *
   * A merged LOG is a different case, and it is safe for a reason already written
   * down: rule 3 of this store says finishing twice is one workout, because the id
   * is the session's own. So a union keyed on id cannot produce two rows for one
   * workout, which is the failure mode that makes merging a library unauditable. A
   * replaced phone and a second device become serviceable, and nothing else changes.
   *
   * ON A COLLISION THE LOCAL COPY WINS. The row on this phone is the one whose
   * corrections, if any, were made here — and "the file is authoritative" is what
   * `importWorkouts` is for. Merging is additive by definition: it never rewrites a
   * row that is already here.
   */
  mergeWorkouts: (raw: unknown) => number;
}

/**
 * The log, read out of SQLite before the first render.
 *
 * SYNCHRONOUS, which is the visible win of the move: under AsyncStorage the store
 * started empty and filled in a frame later, so the History tab flickered from
 * "Nothing finished yet" to a full list on every launch. `expo-sqlite`'s sync API
 * means the array is already there the first time a screen reads it.
 *
 * Guarded, because this runs at module scope. A throw here — a corrupt database
 * file, an OS error opening it — would be a crash on launch before any
 * `ErrorBoundary` exists, which is the exact failure mode `App.tsx` wraps its
 * notification handler against. An empty log is recoverable; a process that dies
 * at import is not, and the AsyncStorage key is still on disk either way.
 */
function loadWorkouts(): CompletedWorkout[] {
  try {
    return sanitizeWorkouts(readAllWorkouts(), []);
  } catch {
    return [];
  }
}

/**
 * Where the pinned workout number lives on disk.
 *
 * The `meta` table rather than a row on a workout, because the anchor is a fact
 * about the LOG and not about the session it points at: exactly one exists, and
 * storing it beside the workout would make "which of these is the anchor" a scan
 * with no constraint stopping a second one appearing.
 *
 * It does NOT travel through the zustand `persist` middleware the rest of the app
 * uses. That middleware is gone from this store — rule 6 — and re-adding it for one
 * key would put half this store's state in SQLite and half in AsyncStorage, which
 * is the arrangement whose failure modes rule 4 exists to avoid.
 */
const NUMBERING_KEY = 'workout-numbering';

/** The pin, off disk, guarded exactly as the workouts are. Never throws. */
function loadNumbering(workouts: readonly CompletedWorkout[]): WorkoutNumberAnchor | null {
  try {
    const raw = readMeta(NUMBERING_KEY);
    return raw == null ? null : sanitizeNumbering(JSON.parse(raw), workouts);
  } catch {
    return null;
  }
}

/**
 * Persist the pin, and hand it back so callers can put it in the same `set` as the
 * workouts it was validated against — the database first, as everywhere else here.
 */
function persistNumbering(anchor: WorkoutNumberAnchor | null): WorkoutNumberAnchor | null {
  writeMeta(NUMBERING_KEY, JSON.stringify(anchor));
  return anchor;
}

const initialWorkouts = loadWorkouts();

export const useWorkoutHistory = create<WorkoutHistoryState>()((set, get) => ({
  workouts: initialWorkouts,
  numbering: loadNumbering(initialWorkouts),

  saveSession: (session, endedAt) => {
    /*
     * The bodyweight is read HERE rather than passed in by a screen, for the
     * same reason `completeSet` reads the rest lengths here: it is a setting,
     * the screen has no opinion about it, and wiring it through props would
     * make every caller responsible for a number it does not own. Volume is
     * computed once from the value the app has at this instant and never
     * recomputed — history is not rewritten when a setting changes.
     */
    const workout = buildCompletedWorkout(session, endedAt, currentSettings().bodyweightKg ?? null);
    if (!workout) return null;

    /*
     * The DATABASE first, then the in-memory array. In that order deliberately:
     * the write is what has to survive the process dying, and a state update that
     * lands before a write that throws is a screen showing a workout that is not
     * on disk. `writeWorkouts` is one transaction, so it either happened or it did
     * not.
     */
    writeWorkouts([workout]);

    const withoutDuplicate = get().workouts.filter((w) => w.id !== workout.id);
    set({
      workouts: [workout, ...withoutDuplicate].sort(
        (a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime(),
      ),
    });
    return workout;
  },

  /**
   * Delete one workout.
   *
   * If it was the workout the numbering was pinned to, the pin MOVES to a
   * neighbour carrying the number that neighbour already had — otherwise deleting
   * the one session someone had numbered would silently reset the whole column to
   * "the oldest is 1". Every surviving number stays exactly where it was, which is
   * the point of moving it rather than dropping it.
   */
  deleteWorkout: (id) => {
    const { workouts, numbering } = get();
    deleteWorkoutRow(id);
    const remaining = workouts.filter((w) => w.id !== id);

    if (!numbering || numbering.workoutId !== id) {
      set({ workouts: remaining });
      return;
    }

    const numbers = workoutNumbers(workouts, numbering);
    const index = workouts.findIndex((w) => w.id === id);
    // The workout just newer than the one going, or just older if it was the
    // newest. Both keep every surviving number where it was.
    const heir = workouts[index - 1] ?? workouts[index + 1] ?? null;
    set({
      workouts: remaining,
      numbering: persistNumbering(heir ? { workoutId: heir.id, number: numbers[heir.id] } : null),
    });
  },

  updateWorkoutSet: (workoutId, setId, patch) => {
    const workout = get().workouts.find((w) => w.id === workoutId);
    if (!workout) return false;
    if (!workout.sets.some((row) => row.id === setId)) return false;

    const sets = workout.sets.map((row) => {
      if (row.id !== setId) return row;
      return {
        ...row,
        // `undefined` means "not in the patch"; `null` is a real weight for an
        // unweighted set, so the two cannot be collapsed.
        ...(patch.weightKg !== undefined ? { weightKg: patch.weightKg } : {}),
        ...(patch.count !== undefined ? { count: Math.max(0, Math.round(patch.count)) } : {}),
        ...(patch.isWarmup !== undefined ? { isWarmup: patch.isWarmup } : {}),
      };
    });

    return writeRecomputed(set, get, workoutId, sets);
  },

  deleteWorkoutSet: (workoutId, setId) => {
    const workout = get().workouts.find((w) => w.id === workoutId);
    if (!workout) return false;
    if (!workout.sets.some((row) => row.id === setId)) return false;
    /*
     * The last row takes the workout with it — so it is refused here rather
     * than done quietly. `deleteWorkout` exists, it is one tap away inside the
     * same expanded row, and it asks first; a set row's ✕ silently deleting a
     * session would be the one destructive action in the app that does not.
     */
    if (workout.sets.length <= 1) return false;

    return writeRecomputed(
      set,
      get,
      workoutId,
      workout.sets.filter((row) => row.id !== setId),
    );
  },

  clearHistory: () => {
    clearAllWorkouts();
    // The pin points at a workout that has just stopped existing.
    set({ workouts: [], numbering: persistNumbering(null) });
  },

  setWorkoutNumber: (id, number) => {
    const rounded = Math.round(number);
    if (!Number.isFinite(rounded) || rounded < 1) return;
    if (!get().workouts.some((w) => w.id === id)) return;
    set({ numbering: persistNumbering({ workoutId: id, number: rounded }) });
  },

  clearWorkoutNumbering: () => set({ numbering: persistNumbering(null) }),

  importWorkouts: (raw, numbering) => {
    // The same guard the database read uses: a file off an SD card is exactly as
    // trustworthy as a column off disk, and one validator cannot disagree with
    // itself. See `sanitizeWorkouts`.
    const workouts = sanitizeWorkouts(raw, []);
    // One transaction: a restore that throws halfway leaves the previous log
    // intact rather than half of each.
    replaceAllWorkouts(workouts);
    // Validated against the workouts that actually survived, not the ones the file
    // claimed: a pin onto a workout the guard dropped is a pin onto nothing.
    set({ workouts, numbering: persistNumbering(sanitizeNumbering(numbering, workouts)) });
    return workouts.length;
  },

  mergeWorkouts: (raw) => {
    // Same validator, same reason: a file off an SD card is exactly as
    // trustworthy as a column off disk, and there is one guard per shape.
    const incoming = sanitizeWorkouts(raw, []);
    if (incoming.length === 0) return 0;

    const local = get().workouts;
    const known = new Set(local.map((w) => w.id));
    const added = incoming.filter((w) => !known.has(w.id));
    if (added.length === 0) return 0;

    writeWorkouts(added);
    set({
      workouts: [...local, ...added].sort(
        (a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime(),
      ),
    });
    return added.length;
  },
}));

/**
 * Bring the AsyncStorage log across, once, and refresh the store from what landed.
 *
 * Called from `App.tsx` rather than run at module scope: it is async (AsyncStorage
 * is), it touches two storage systems, and a side effect of that size hiding inside
 * an import is how a launch crash becomes hard to place.
 *
 * `migrateFromAsyncStorage` is where the paranoia lives — one transaction, read
 * back and counted before anything is recorded as done, and the old key never
 * deleted. This function's only job is to hand it the store's own validator, so
 * there is still exactly one guard per shape, and to re-read the log if anything
 * moved.
 *
 * Failure is silent on purpose. A migration that could not run leaves the old key
 * where it is and tries again next launch; there is nothing the user could do about
 * it, and a dialog on launch about a storage system they have never heard of is
 * worse than an empty History that fills itself in tomorrow.
 */
export async function migrateHistoryIfNeeded(): Promise<void> {
  try {
    const outcome = await migrateFromAsyncStorage((raw) => sanitizeWorkouts(raw, []));
    if (outcome.status !== 'migrated') return;
    const workouts = sanitizeWorkouts(readAllWorkouts(), []);
    /*
     * The pin comes across with the log. It rode in the same AsyncStorage blob, and
     * a migration that moved every workout but renumbered all of them is a worse
     * outcome than one that moved nothing — see `legacyNumbering`. Validated here,
     * against the workouts that actually landed, because the guard lives in this
     * store and there is one per shape.
     */
    useWorkoutHistory.setState({
      workouts,
      numbering: persistNumbering(sanitizeNumbering(outcome.legacyNumbering, workouts)),
    });
  } catch {
    // See above: next launch tries again, from a key that is still there.
  }
}

/**
 * Write a corrected row list back, with every derived number regenerated.
 *
 * The one place both correction actions go through, so neither can forget the
 * recompute. `recomputeWorkout` runs the SAME functions that built the record —
 * `summarizeSessionSets` for the shorthand, `effectiveLoadKg` for the load —
 * against the rows as they now are; nothing here patches a rendered string.
 *
 * The BODYWEIGHT is read live, and that is deliberate: a workout logged before the
 * user typed one has `volumeIsPartial` set, and correcting a row is the moment the
 * figure is being recomputed anyway. It is not a backfill — nothing recomputes on
 * its own, and a workout nobody edits keeps the number it was recorded with.
 *
 * A recompute that leaves no exercises means every row was a warm-up, which
 * `buildCompletedWorkout` refuses to record in the first place. Written anyway
 * rather than special-cased: the rows are the user's, and a workout that reads
 * "0 sets" after they marked everything a warm-up is exactly what they asked for.
 */
function writeRecomputed(
  set: (partial: Partial<WorkoutHistoryState>) => void,
  get: () => WorkoutHistoryState,
  workoutId: ID,
  sets: SetHistory[],
): boolean {
  const bodyweightKg = currentSettings().bodyweightKg ?? null;
  const workouts = get().workouts.map((w) =>
    w.id === workoutId ? recomputeWorkout({ ...w, sets }, bodyweightKg) : w,
  );

  /*
   * The database first, as everywhere else in this store: a state update that lands
   * before a write that throws is a screen showing a correction that is not on
   * disk. `writeWorkouts` deletes and reinserts the row list inside one
   * transaction, which is what stops a removed set surviving as an orphan.
   */
  const corrected = workouts.find((w) => w.id === workoutId);
  if (corrected) writeWorkouts([corrected]);

  set({ workouts });
  return true;
}

/* ------------------------------------------------------------------ */
/* Guards on everything that comes from outside                        */
/* ------------------------------------------------------------------ */

/**
 * A renderable, newest-first log out of anything at all — database rows, a backup
 * file, or a legacy AsyncStorage blob during the migration. `fallback` is what a
 * MISSING array becomes.
 *
 * No `.slice()` any more: the cap is gone with the blob that needed it (rule 6).
 * Everything else about this function is unchanged, because moving the bytes into
 * columns does not make them trustworthy — see rule 4.
 */
function sanitizeWorkouts(raw: unknown, fallback: CompletedWorkout[]): CompletedWorkout[] {
  if (!Array.isArray(raw)) return fallback;
  return raw
    .map(sanitizeWorkout)
    .filter((w): w is CompletedWorkout => w !== null)
    .sort((a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime());
}

/**
 * A pin that still points at something, or null.
 *
 * Dropped rather than repaired when the workout is gone: the anchor's whole
 * meaning is "THIS session is number N", and keeping the number while losing the
 * session it belonged to would renumber the log by an arbitrary offset.
 */
function sanitizeNumbering(
  value: unknown,
  workouts: readonly CompletedWorkout[],
): WorkoutNumberAnchor | null {
  if (typeof value !== 'object' || value === null) return null;
  const raw = value as Partial<WorkoutNumberAnchor>;
  if (typeof raw.workoutId !== 'string') return null;
  if (typeof raw.number !== 'number' || !Number.isFinite(raw.number)) return null;
  const number = Math.round(raw.number);
  if (number < 1) return null;
  if (!workouts.some((w) => w.id === raw.workoutId)) return null;
  return { workoutId: raw.workoutId, number };
}

const COUNT_UNITS = new Set(['reps', 'seconds', 'meters', 'rounds']);
const LOAD_MODES = new Set(['external', 'added_bodyweight', 'assisted', 'none']);

function finiteOr(value: unknown, fallback: number): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

function isIsoish(value: unknown): value is string {
  return typeof value === 'string' && Number.isFinite(new Date(value).getTime());
}

/**
 * A workout the history screen can render, or null.
 *
 * Repaired rather than rejected wherever the damage is cosmetic — a missing
 * duration is a number, not a reason to lose the record of a session that
 * happened. Rejected only when the thing that identifies it (an id, a title, a
 * date) is not there, because a row that cannot say what or when it was is not a
 * record of anything.
 */
function sanitizeWorkout(value: unknown): CompletedWorkout | null {
  if (typeof value !== 'object' || value === null) return null;
  const raw = value as Partial<CompletedWorkout>;

  if (typeof raw.id !== 'string' || typeof raw.title !== 'string') return null;
  if (!isIsoish(raw.startedAt)) return null;

  const sets = Array.isArray(raw.sets)
    ? raw.sets.map(sanitizeSetRow).filter((row): row is SetHistory => row !== null)
    : [];
  const exercises = Array.isArray(raw.exercises)
    ? raw.exercises
        .map((exercise) => sanitizeCompletedExercise(exercise, sets))
        .filter((e): e is CompletedExercise => e !== null)
    : [];

  return {
    id: raw.id,
    title: raw.title,
    ...(typeof raw.routineId === 'string' ? { routineId: raw.routineId } : {}),
    startedAt: raw.startedAt,
    endedAt: isIsoish(raw.endedAt) ? raw.endedAt : raw.startedAt,
    durationMinutes: Math.max(1, Math.round(finiteOr(raw.durationMinutes, 1))),
    setCount: Math.max(0, Math.round(finiteOr(raw.setCount, sets.length))),
    totalVolumeKg: Math.max(0, Math.round(finiteOr(raw.totalVolumeKg, 0))),
    /*
     * `volumeIsPartial` arrived in 0.12.0, so every workout logged before it has a
     * volume figure and no flag. Deriving it is exact rather than a guess: volume
     * used to skip every exercise with `requiresWeight === false` and read
     * assistance as load, so a pre-0.11 workout containing ANY rep-counted set
     * that is not plain external work has a total that undercounts. That is
     * precisely what the flag means.
     */
    volumeIsPartial:
      typeof raw.volumeIsPartial === 'boolean'
        ? raw.volumeIsPartial
        : sets.some((row) => row.countUnit === 'reps' && row.loadMode !== 'external'),
    exercises,
    sets,
  };
}

/**
 * `rows` are the workout's own set rows, and they are what makes `totalCount`
 * survive an upgrade: the field was added in 0.10.0, so every workout logged
 * before it has a summary and no total. Summing the rows recovers the real number
 * rather than showing a 0 for training that happened.
 */
function sanitizeCompletedExercise(
  value: unknown,
  rows: readonly SetHistory[],
): CompletedExercise | null {
  if (typeof value !== 'object' || value === null) return null;
  const raw = value as Partial<CompletedExercise>;
  if (typeof raw.exerciseId !== 'string' || typeof raw.name !== 'string') return null;
  if (typeof raw.summary !== 'string') return null;

  return {
    exerciseId: raw.exerciseId,
    name: raw.name,
    countUnit: COUNT_UNITS.has(raw.countUnit as string) ? raw.countUnit! : 'reps',
    loadMode: LOAD_MODES.has(raw.loadMode as string) ? raw.loadMode! : 'none',
    setCount: Math.max(0, Math.round(finiteOr(raw.setCount, 0))),
    summary: raw.summary,
    totalCount: Math.max(
      0,
      finiteOr(
        raw.totalCount,
        rows
          // Working sets only, matching what `buildCompletedWorkout` writes: a
          // warm-up is a set that does not count, so it must not appear in a
          // total recovered from the rows either.
          .filter((row) => row.exerciseId === raw.exerciseId && !row.isWarmup)
          .reduce((sum, row) => sum + row.count, 0),
      ),
    ),
    topWeightKg:
      typeof raw.topWeightKg === 'number' && Number.isFinite(raw.topWeightKg)
        ? raw.topWeightKg
        : null,
  };
}

/**
 * One set row, rebuilt FIELD BY FIELD, or null.
 *
 * Stricter than the workout around it: these rows are the input to every future
 * suggestion the app makes, and one row with a `NaN` count would poison a verdict
 * rather than break a screen — which is harder to notice and worse. A row missing
 * anything the overload engine or the shorthand indexes into is dropped whole.
 *
 * NAMED KEYS, NOT A SPREAD, and that is the change 0.12.0 made here. This used to
 * be a predicate feeding `{ ...row, isCompleted: true }`, which validated the
 * fields it knew about and copied everything else straight through — so
 * `estimated1RM`, `rpe`, `side`, `partials` and `notes`, all deleted from
 * `SetHistory` this release, would have ridden along in memory out of an old
 * persisted blob or an old backup file and been written back to disk on the next
 * save, forever. Listing the keys is the same argument `sanitizeSettings` makes
 * about `partialize`: a spread writes things you did not mean to write. A field
 * added to `SetHistory` without being named here is now a type error rather than
 * an unchecked value reaching a verdict.
 */
function sanitizeSetRow(value: unknown): SetHistory | null {
  if (typeof value !== 'object' || value === null) return null;
  const row = value as Partial<SetHistory>;

  if (typeof row.id !== 'string') return null;
  if (typeof row.sessionId !== 'string' || typeof row.exerciseId !== 'string') return null;
  if (!isIsoish(row.performedAt)) return null;
  if (!Number.isFinite(row.setIndex) || !Number.isFinite(row.count)) return null;
  if (row.weightKg != null && !Number.isFinite(row.weightKg)) return null;
  if (!COUNT_UNITS.has(row.countUnit as string)) return null;
  if (!LOAD_MODES.has(row.loadMode as string)) return null;
  if (typeof row.isWarmup !== 'boolean') return null;

  return {
    id: row.id,
    sessionId: row.sessionId,
    exerciseId: row.exerciseId,
    performedAt: row.performedAt,
    setIndex: row.setIndex as number,
    weightKg: row.weightKg ?? null,
    count: row.count as number,
    countUnit: row.countUnit as CountUnit,
    loadMode: row.loadMode as LoadMode,
    isWarmup: row.isWarmup,
    // Only completed sets are ever written (`draftToSetHistory`), so a row in the
    // log is a set that happened whatever the blob claims.
    isCompleted: true,
    ...(typeof row.restTakenSeconds === 'number' && Number.isFinite(row.restTakenSeconds)
      ? { restTakenSeconds: Math.max(0, Math.round(row.restTakenSeconds)) }
      : {}),
  };
}

/* ------------------------------------------------------------------ */
/* Derived                                                             */
/* ------------------------------------------------------------------ */

export interface HistoryTotals {
  workouts: number;
  sets: number;
  volumeKg: number;
  /**
   * True when at least one workout in the log carries a volume figure that is
   * known to undercount — see `CompletedWorkout.volumeIsPartial`. The screen
   * omits the volume clause entirely rather than printing a sum of numbers some of
   * which are missing their bodyweight half.
   */
  volumeIsPartial: boolean;
}

/** The one line above the list: how much training is actually in here. */
export function historyTotals(workouts: readonly CompletedWorkout[]): HistoryTotals {
  let sets = 0;
  let volumeKg = 0;
  let volumeIsPartial = false;
  for (const workout of workouts) {
    sets += workout.setCount;
    volumeKg += workout.totalVolumeKg;
    if (workout.volumeIsPartial) volumeIsPartial = true;
  }
  return { workouts: workouts.length, sets, volumeKg, volumeIsPartial };
}

/**
 * The home screen's `RECENT` rows.
 *
 * A different type on purpose — four fields, no set rows. See the note on
 * `RecentSessionSummary`.
 */
export function recentSummaries(
  workouts: readonly CompletedWorkout[],
  limit = 4,
): RecentSessionSummary[] {
  return workouts.slice(0, limit).map((workout) => ({
    id: workout.id,
    title: workout.title,
    performedAt: workout.startedAt,
    durationMinutes: workout.durationMinutes,
  }));
}
